# Non Graded Challenge 11


 `Name               : Reyki Seprianza`
 `Batch              : FTDS009`

----------------------------
Non-Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program khususnya pada konsep Descriptive.

## Assignment Instructions
- Unduh dataset yang akan dipakai [disini](https://www.kaggle.com/hendratno/covid19-indonesia)
- Cari Measure of Central Tendency dari data tersebut.
- Cari Measure of Variance dari data tersebut.


## Assignment Submission
Simpan assignment pada sesi ini dengan nama h8dsft_Descriptive.
Push Assigment yang telah kalian buat ke akun Github kalian masing-masing.


## Assignment Objectives
Non-Graded Assignment ini dibuat guna mengevaluasi konsep Descriptive sebagai berikut:

- Memahami konsep Measure of Central Tendency dan implementasinya dengan Python
- Memahami konsep Measure of Variance dan implementasinya dengan Python

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('covid_19_indonesia_time_series_all.csv')
df.head()

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,41,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,105.13%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,41,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,100.00%,1.0,1.0
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,2,0,3,...,0.511648,0.16,0.33,0.0,0.00,0.00,0.00%,150.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,41,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,95.35%,1.0,1.0

In [3]:
df.shape

(21759, 38)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21759 entries, 0 to 21758
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         21759 non-null  object
 1   Location ISO Code            21759 non-null  object
 2   Location                     21759 non-null  object
 3   New Cases                    21759 non-null  int64
 4   New Deaths                   21759 non-null  int64
 5   New Recovered                21759 non-null  int64
 6   New Active Cases             21759 non-null  int64
 7   Total Cases                  21759 non-null  int64
 8   Total Deaths                 21759 non-null  int64
 9   Total Recovered              21759 non-null  int64
 10  Total Active Cases           21759 non-null  int64
 11  Location Level               21759 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     21117 non-null  object
 14  Country                      21759 non-null  object
 15  Continent                    21759 non-null  object
 16  Island                       21117 non-null  object
 17  Time Zone                    21117 non-null  object
 18  Special Status               3123 non-null   object
 19  Total Regencies              21759 non-null  int64
 20  Total Cities                 21145 non-null  float64
 21  Total Districts              21759 non-null  int64
 22  Total Urban Villages         21142 non-null  float64
 23  Total Rural Villages         21117 non-null  float64
 24  Area (km2)                   21759 non-null  int64
 25  Population                   21759 non-null  int64
 26  Population Density           21759 non-null  float64
 27  Longitude                    21759 non-null  float64
 28  Latitude                     21759 non-null  float64
 29  New Cases per Million        21759 non-null  float64
 30  Total Cases per Million      21759 non-null  float64
 31  New Deaths per Million       21759 non-null  float64
 32  Total Deaths per Million     21759 non-null  float64
 33  Total Deaths per 100rb       21759 non-null  float64
 34  Case Fatality Rate           21759 non-null  object
 35  Case Recovered Rate          21759 non-null  object
 36  Growth Factor of New Cases   20572 non-null  float64
 37  Growth Factor of New Deaths  19292 non-null  float64
dtypes: float64(14), int64(12), object(12)
memory usage: 6.3+ MB

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
New Cases,21759.0,3.912936e+02,2.074551e+03,0.000000,7.000000e+00,4.100000e+01,1.510000e+02,5.675700e+04
New Deaths,21759.0,1.322041e+01,7.648262e+01,0.000000,0.000000e+00,1.000000e+00,5.000000e+00,2.069000e+03
New Recovered,21759.0,3.773110e+02,1.999063e+03,0.000000,4.000000e+00,3.100000e+01,1.430000e+02,4.883200e+04
New Active Cases,21759.0,7.621674e-01,9.372135e+02,-25725.000000,-1.600000e+01,0.000000e+00,2.700000e+01,3.672600e+04
Total Cases,21759.0,8.525997e+04,3.685133e+05,1.000000,1.822500e+03,1.078000e+04,3.646450e+04,4.257243e+06
Total Deaths,21759.0,2.648289e+03,1.177601e+04,0.000000,5.000000e+01,2.830000e+02,1.050000e+03,1.438580e+05
Total Recovered,21759.0,7.671260e+04,3.403957e+05,0.000000,1.038500e+03,8.745000e+03,3.293250e+04,4.105680e+06
Total Active Cases,21759.0,5.899079e+03,2.751810e+04,-2306.000000,1.820000e+02,9.190000e+02,2.607500e+03,5.741350e+05
City or Regency,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Regencies,21759.0,2.416026e+01,6.870827e+01,1.000000,7.000000e+00,1.100000e+01,1.800000e+01,4.160000e+02
Total Cities,21145.0,5.872499e+00,1.647141e+01,1.000000,1.000000e+00,2.000000e+00,4.000000e+00,9.800000e+01
Total Districts,21759.0,4.204444e+02,1.199019e+03,44.000000,1.030000e+02,1.690000e+02,2.890000e+02,7.230000e+03
Total Urban Villages,21142.0,5.087405e+02,1.429128e+03,35.000000,9.900000e+01,1.750000e+02,3.320000e+02,8.488000e+03
Total Rural Villages,21117.0,4.490348e+03,1.264756e+04,275.000000,9.280000e+02,1.591000e+03,2.853000e+03,7.495300e+04
Area (km2),21759.0,1.112418e+05,3.203746e+05,664.000000,1.678700e+04,4.201300e+04,7.546800e+04,1.916907e+06
Population,21759.0,1.547817e+07,4.483574e+07,648407.000000,1.999539e+06,4.216171e+06,9.095591e+06,2.651855e+08
Population Density,21759.0,7.449898e+02,2.743210e+03,8.590000,4.779000e+01,1.038400e+02,2.627000e+02,1.633431e+04
Longitude,21759.0,1.136808e+02,9.857587e+00,96.910522,1.061090e+02,1.134177e+02,1.212011e+02,1.386960e+02
Latitude,21759.0,-2.731868e+00,3.608264e+00,-8.682205,-6.204699e+00,-2.461746e+00,2.120369e-01,4.225615e+00
New Cases per Million,21759.0,2.939303e+01,6.994109e+01,0.000000,1.750000e+00,8.160000e+00,2.626000e+01,1.348130e+03
Total Cases per Million,21759.0,6.183651e+03,1.028812e+04,0.010000,4.159150e+02,2.727460e+03,7.374120e+03,7.966379e+04
New Deaths per Million,21759.0,8.527267e-01,2.277310e+00,0.000000,0.000000e+00,1.800000e-01,7.500000e-01,6.380000e+01
Total Deaths per Million,21759.0,1.635422e+02,2.541958e+02,0.000000,1.088000e+01,7.355000e+01,1.958500e+02,1.533980e+03
Total Deaths per 100rb,21759.0,1.635419e+01,2.541960e+01,0.000000,1.090000e+00,7.350000e+00,1.958500e+01,1.534000e+02
Growth Factor of New Cases,20572.0,1.395671e+00,3.080207e+00,0.000000,6.500000e-01,9.900000e-01,1.330000e+00,1.750000e+02
Growth Factor of New Deaths,19292.0,1.074145e+00,1.578502e+00,0.000000,6.600000e-01,1.000000e+00,1.000000e+00,1.345000e+02

In [8]:
df.fillna(0,inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21759 entries, 0 to 21758
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         21759 non-null  object
 1   Location ISO Code            21759 non-null  object
 2   Location                     21759 non-null  object
 3   New Cases                    21759 non-null  int64
 4   New Deaths                   21759 non-null  int64
 5   New Recovered                21759 non-null  int64
 6   New Active Cases             21759 non-null  int64
 7   Total Cases                  21759 non-null  int64
 8   Total Deaths                 21759 non-null  int64
 9   Total Recovered              21759 non-null  int64
 10  Total Active Cases           21759 non-null  int64
 11  Location Level               21759 non-null  object
 12  City or Regency              21759 non-null  float64
 13  Province                     21759 non-null  object
 14  Country                      21759 non-null  object
 15  Continent                    21759 non-null  object
 16  Island                       21759 non-null  object
 17  Time Zone                    21759 non-null  object
 18  Special Status               21759 non-null  object
 19  Total Regencies              21759 non-null  int64
 20  Total Cities                 21759 non-null  float64
 21  Total Districts              21759 non-null  int64
 22  Total Urban Villages         21759 non-null  float64
 23  Total Rural Villages         21759 non-null  float64
 24  Area (km2)                   21759 non-null  int64
 25  Population                   21759 non-null  int64
 26  Population Density           21759 non-null  float64
 27  Longitude                    21759 non-null  float64
 28  Latitude                     21759 non-null  float64
 29  New Cases per Million        21759 non-null  float64
 30  Total Cases per Million      21759 non-null  float64
 31  New Deaths per Million       21759 non-null  float64
 32  Total Deaths per Million     21759 non-null  float64
 33  Total Deaths per 100rb       21759 non-null  float64
 34  Case Fatality Rate           21759 non-null  object
 35  Case Recovered Rate          21759 non-null  object
 36  Growth Factor of New Cases   21759 non-null  float64
 37  Growth Factor of New Deaths  21759 non-null  float64
dtypes: float64(14), int64(12), object(12)
memory usage: 6.3+ MB

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
New Cases,21759.0,3.912936e+02,2.074551e+03,0.000000,7.000000e+00,4.100000e+01,1.510000e+02,5.675700e+04
New Deaths,21759.0,1.322041e+01,7.648262e+01,0.000000,0.000000e+00,1.000000e+00,5.000000e+00,2.069000e+03
New Recovered,21759.0,3.773110e+02,1.999063e+03,0.000000,4.000000e+00,3.100000e+01,1.430000e+02,4.883200e+04
New Active Cases,21759.0,7.621674e-01,9.372135e+02,-25725.000000,-1.600000e+01,0.000000e+00,2.700000e+01,3.672600e+04
Total Cases,21759.0,8.525997e+04,3.685133e+05,1.000000,1.822500e+03,1.078000e+04,3.646450e+04,4.257243e+06
Total Deaths,21759.0,2.648289e+03,1.177601e+04,0.000000,5.000000e+01,2.830000e+02,1.050000e+03,1.438580e+05
Total Recovered,21759.0,7.671260e+04,3.403957e+05,0.000000,1.038500e+03,8.745000e+03,3.293250e+04,4.105680e+06
Total Active Cases,21759.0,5.899079e+03,2.751810e+04,-2306.000000,1.820000e+02,9.190000e+02,2.607500e+03,5.741350e+05
City or Regency,21759.0,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Total Regencies,21759.0,2.416026e+01,6.870827e+01,1.000000,7.000000e+00,1.100000e+01,1.800000e+01,4.160000e+02
Total Cities,21759.0,5.706788e+00,1.626644e+01,0.000000,1.000000e+00,2.000000e+00,4.000000e+00,9.800000e+01
Total Districts,21759.0,4.204444e+02,1.199019e+03,44.000000,1.030000e+02,1.690000e+02,2.890000e+02,7.230000e+03
Total Urban Villages,21759.0,4.943146e+02,1.411248e+03,0.000000,9.500000e+01,1.720000e+02,3.320000e+02,8.488000e+03
Total Rural Villages,21759.0,4.357860e+03,1.248272e+04,0.000000,8.410000e+02,1.507000e+03,2.853000e+03,7.495300e+04
Area (km2),21759.0,1.112418e+05,3.203746e+05,664.000000,1.678700e+04,4.201300e+04,7.546800e+04,1.916907e+06
Population,21759.0,1.547817e+07,4.483574e+07,648407.000000,1.999539e+06,4.216171e+06,9.095591e+06,2.651855e+08
Population Density,21759.0,7.449898e+02,2.743210e+03,8.590000,4.779000e+01,1.038400e+02,2.627000e+02,1.633431e+04
Longitude,21759.0,1.136808e+02,9.857587e+00,96.910522,1.061090e+02,1.134177e+02,1.212011e+02,1.386960e+02
Latitude,21759.0,-2.731868e+00,3.608264e+00,-8.682205,-6.204699e+00,-2.461746e+00,2.120369e-01,4.225615e+00
New Cases per Million,21759.0,2.939303e+01,6.994109e+01,0.000000,1.750000e+00,8.160000e+00,2.626000e+01,1.348130e+03
Total Cases per Million,21759.0,6.183651e+03,1.028812e+04,0.010000,4.159150e+02,2.727460e+03,7.374120e+03,7.966379e+04
New Deaths per Million,21759.0,8.527267e-01,2.277310e+00,0.000000,0.000000e+00,1.800000e-01,7.500000e-01,6.380000e+01
Total Deaths per Million,21759.0,1.635422e+02,2.541958e+02,0.000000,1.088000e+01,7.355000e+01,1.958500e+02,1.533980e+03
Total Deaths per 100rb,21759.0,1.635419e+01,2.541960e+01,0.000000,1.090000e+00,7.350000e+00,1.958500e+01,1.534000e+02
Growth Factor of New Cases,21759.0,1.319534e+00,3.011735e+00,0.000000,5.600000e-01,9.600000e-01,1.290000e+00,1.750000e+02
Growth Factor of New Deaths,21759.0,9.523604e-01,1.524842e+00,0.000000,2.800000e-01,1.000000e+00,1.000000e+00,1.345000e+02

In [11]:
# visualize label count in each category
for i in ['Total Recovered', 'City or Regency', 'Total Deaths']:
    print(i, ':')
    print(df[i].value_counts())
    print('-'*50)

Total Recovered :
0          258
1          178
2          168
3          108
4          100
          ...
3513         1
1464         1
60853        1
23987        1
1481449      1
Name: Total Recovered, Length: 14152, dtype: int64
--------------------------------------------------
City or Regency :
0.0    21759
Name: City or Regency, dtype: int64
--------------------------------------------------
Total Deaths :
1         547
2         505
0         443
4         324
3         320
         ...
38049       1
2520        1
143807      1
10684       1
2039        1
Name: Total Deaths, Length: 4526, dtype: int64
--------------------------------------------------

In [18]:
df2= df.groupby('Province')['Total Recovered','Total Deaths'].sum()
df2

C:\Users\acer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

                            Total Recovered  Total Deaths
Province
0                                 835755581      28738435
Aceh                                6522985        360497
Bali                               21432901        743026
Banten                             24682144        604657
Bengkulu                            4034033         97985
DKI Jakarta                       197475361       3420849
Daerah Istimewa Yogyakarta         24551712        853993
Gorontalo                           2569824         92510
Jambi                               4747259        123556
Jawa Barat                        136201392       2653330
Jawa Tengah                        88998394       5687699
Jawa Timur                         77904298       6482760
Kalimantan Barat                    6308741        149422
Kalimantan Selatan                 14621137        540913
Kalimantan Tengah                   8895952        279728
Kalimantan Timur                   31284556       1029837
Kalimantan Utara                    5708443        125859
Kepulauan Bangka Belitung           8172432        207668
Kepulauan Riau                      9190746        291105
Lampung                             8132246        631393
Maluku                              3499078         64634
Maluku Utara                        2420767         74370
Nusa Tenggara Barat                 5361080        210638
Nusa Tenggara Timur                 9359584        224849
Papua                               6217275        134431
Papua Barat                         4817872         82576
Riau                               24923162        772172
Sulawesi Barat                      2395009         63429
Sulawesi Selatan                   26343555        527722
Sulawesi Tengah                     7027539        249549
Sulawesi Tenggara                   4766242        118203
Sulawesi Utara                      7103942        264951
Sumatera Barat                     18805743        469542
Sumatera Selatan                   11364511        646452
Sumatera Utara                     17594021        605388

### Central Tendency

In [21]:
df2.describe()

       Total Recovered  Total Deaths
count     3.500000e+01  3.500000e+01
mean      4.769113e+07  1.646404e+06
std       1.430931e+08  4.941153e+06
min       2.395009e+06  6.342900e+04
25%       5.534762e+06  1.301450e+05
50%       8.895952e+06  2.911050e+05
75%       2.461693e+07  6.947390e+05
max       8.357556e+08  2.873844e+07

Disini bisa kita lihat total yang sembuh lebih banyak dari yang meninggal di seluruh indonesia alhamdulilah ya

### Variance dari data sembuh dan meninggal di tiap provinsi

In [22]:
df2['Total Recovered'].var()

2.0475642865228864e+16

In [23]:
df2['Total Deaths'].var()

24414988553754.652